# Generated by Django 3.0.3 on 2020-02-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transação'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transação',
            new_name='Transacao',
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transacoes'},
        ),
    ]
