# Generated by Django 3.0.3 on 2020-02-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20200218_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
