# Generated by Django 3.0.3 on 2020-02-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_auto_20200218_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='date',
            new_name='data',
        ),
    ]
