# Generated by Django 3.0.3 on 2020-02-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20200218_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'transacoes'},
        ),
    ]
